-- Activa’t independent Supabase schema and Sites data migration.
-- Every object is prefixed activa_t_ so the existing Activa app is untouched.
create schema if not exists activa_t_private;

create table if not exists public.activa_t_activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_id bigint,
  type text not null,
  activity_date date not null,
  start_time text,
  status text not null default 'scheduled' check (status in ('scheduled', 'completed', 'cancelled')),
  ever_cancelled boolean not null default false,
  ever_completed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, legacy_id)
);

create table if not exists public.activa_t_weights (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  legacy_id bigint,
  weight numeric(5,2) not null check (weight > 0 and weight < 500),
  measured_at date not null,
  created_at timestamptz not null default now(),
  unique (user_id, legacy_id)
);

create table if not exists public.activa_t_activity_types (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  icon_key text not null default 'sparkles',
  color text not null default '#65a84f',
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create index if not exists activa_t_activities_user_date_idx on public.activa_t_activities (user_id, activity_date desc);
create index if not exists activa_t_weights_user_date_idx on public.activa_t_weights (user_id, measured_at desc);

alter table public.activa_t_activities enable row level security;
alter table public.activa_t_weights enable row level security;
alter table public.activa_t_activity_types enable row level security;

drop policy if exists "activa_t_activities_owner" on public.activa_t_activities;
create policy "activa_t_activities_owner" on public.activa_t_activities
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "activa_t_weights_owner" on public.activa_t_weights;
create policy "activa_t_weights_owner" on public.activa_t_weights
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "activa_t_activity_types_owner" on public.activa_t_activity_types;
create policy "activa_t_activity_types_owner" on public.activa_t_activity_types
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.activa_t_activities to authenticated;
grant select, insert, update, delete on public.activa_t_weights to authenticated;
grant select, insert, update, delete on public.activa_t_activity_types to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function activa_t_private.seed_anna(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if target_user_id is null then return; end if;

  insert into public.activa_t_activity_types (user_id, name, icon_key, color, hidden)
  select target_user_id, v.name, v.icon_key, v.color, v.hidden
  from (values
    ('Altres', 'sparkles', '#8a72ca', true),
    ('Cinta de córrer', 'run', '#ef6b55', true),
    ('Cinta de còrrer', 'walk', '#ef6b55', false)
  ) as v(name, icon_key, color, hidden)
  where not exists (
    select 1 from public.activa_t_activity_types t
    where t.user_id = target_user_id and t.name = v.name
  );

  insert into public.activa_t_activities
    (user_id, legacy_id, type, activity_date, start_time, status, ever_cancelled, ever_completed)
  select target_user_id, v.legacy_id, v.type, v.activity_date::date, v.start_time, v.status, v.ever_cancelled, v.ever_completed
  from (values
    (5, 'Caminar', '2026-08-30', null, 'completed', false, true),
    (6, 'Caminar', '2026-08-29', null, 'completed', false, true),
    (7, 'Barre', '2026-09-03', null, 'cancelled', true, false),
    (8, 'Spinning', '2026-09-08', null, 'completed', false, true),
    (10, 'Spinning', '2026-09-09', null, 'completed', false, true),
    (11, 'Spinning', '2026-09-15', null, 'cancelled', true, false),
    (12, 'Spinning', '2026-09-16', null, 'completed', false, true),
    (13, 'Caminar', '2026-09-10', '12:45', 'completed', false, true),
    (14, 'Caminar', '2026-09-12', '09:30', 'completed', false, true),
    (16, 'Spinning', '2026-09-22', null, 'completed', false, true),
    (17, 'Spinning', '2026-09-23', null, 'completed', false, true),
    (18, 'Caminar', '2026-09-14', null, 'completed', false, true),
    (19, 'Caminar', '2026-09-15', '12:00', 'completed', false, true),
    (22, 'Spinning', '2026-09-29', null, 'completed', false, true),
    (23, 'Caminar', '2026-09-20', null, 'completed', false, true),
    (24, 'Spinning', '2026-09-30', null, 'cancelled', true, false),
    (25, 'Caminar', '2026-09-27', null, 'completed', false, true),
    (26, 'Spinning', '2026-10-07', null, 'scheduled', false, false)
  ) as v(legacy_id, type, activity_date, start_time, status, ever_cancelled, ever_completed)
  where not exists (
    select 1 from public.activa_t_activities a
    where a.user_id = target_user_id and a.legacy_id = v.legacy_id
  );

  insert into public.activa_t_weights (user_id, legacy_id, weight, measured_at)
  select target_user_id, v.legacy_id, v.weight, v.measured_at::date
  from (values
    (1, 49.5, '2026-08-31'),
    (2, 49.0, '2026-09-08'),
    (3, 48.7, '2026-09-09'),
    (4, 48.4, '2026-09-11'),
    (5, 48.4, '2026-09-12'),
    (6, 48.7, '2026-09-13'),
    (7, 48.8, '2026-09-15'),
    (8, 49.2, '2026-09-18'),
    (9, 49.1, '2026-09-19'),
    (10, 49.8, '2026-09-20'),
    (11, 49.5, '2026-09-21'),
    (12, 48.9, '2026-09-22'),
    (13, 48.7, '2026-09-23'),
    (14, 48.8, '2026-09-29')
  ) as v(legacy_id, weight, measured_at)
  where not exists (
    select 1 from public.activa_t_weights w
    where w.user_id = target_user_id and w.legacy_id = v.legacy_id
  );
end;
$$;

revoke all on schema activa_t_private from public;
revoke all on function activa_t_private.seed_anna(uuid) from public, anon, authenticated;
grant usage on schema activa_t_private to postgres;

drop function if exists activa_t_private.on_user_created();
create or replace function activa_t_private.on_user_created()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if lower(coalesce(new.email, '')) = 'anna.batet.soler@gmail.com' then
    perform activa_t_private.seed_anna(new.id);
  end if;
  return new;
end;
$$;
revoke all on function activa_t_private.on_user_created() from public, anon, authenticated;

drop trigger if exists activa_t_seed_anna on auth.users;
create trigger activa_t_seed_anna
after insert on auth.users
for each row execute function activa_t_private.on_user_created();

-- Also seed Anna if her Google account already exists when this migration runs.
do $$
declare
  anna_id uuid;
begin
  select id into anna_id from auth.users where lower(email) = 'anna.batet.soler@gmail.com' limit 1;
  if anna_id is not null then perform activa_t_private.seed_anna(anna_id); end if;
end;
$$;
